//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Номер_аккаунта { get; set; }
        public int ID_пользователя { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public int Уровень_доступа { get; set; }
    
        public virtual User User { get; set; }
    }
}
