//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LabASP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agreement
    {
        public int Номер_договора { get; set; }
        public int ID_пользователя { get; set; }
        public int Код_товара { get; set; }
        public string ФИО { get; set; }
        public Nullable<System.DateTime> Дата_рождения { get; set; }
        public Nullable<int> Номер_и_серия_паспорта { get; set; }
        public string Адрес { get; set; }
        public string Номер { get; set; }
        public Nullable<System.DateTime> Дата_составления { get; set; }
    
        public virtual User User { get; set; }
        public virtual Product Product { get; set; }
    }
}
